### ISSUE TITLE
nvim-cmp may not set correctly

### ISSUE THREAD

**Issue by rikkaka** [hardhackerlabs/oh-my-nvim#10]
In the [readme of nvim-cmp](https://github.com/hrsh7th/nvim-cmp#setup), it is said that a snippet engine must be specified, and the related plugin should be installed. While in the config file of nvim-cmp, the vsnip engine is specified, but I haven't seen any of the engines is installed somewhere.

https://github.com/hardhackerlabs/oh-my-nvim/blob/c77ddfede1e16b9ac9f6611773f4ec0e98bdee2a/lua/plugins/autocmp/config.lua#L5-L13

And I encountered an error when expand a func completion provided by rust-analyzer.
<img width="1154" alt="image" src="https://github.com/hardhackerlabs/oh-my-nvim/assets/39625849/2244760b-efd2-4f58-83ac-8ea77c43609b">

I checked it and found that it is caused by that the vsnip engine is specified while it is not installed. Then I installed the [LuaSnip](https://github.com/saadparwaiz1/cmp_luasnip) engine and specified it. Then the error is resolved.

So I guess there should be a snippet engine installed and specified, while it is missed in this repo. If there is an error in my configuration, please let me know directly; otherwise, I am happy to fix this problem.

**Comment by skoowoo** [comment]
Thanks for your feedback, could you create a pr? thanks again。
