### ISSUE TITLE
Conflicting keymaps

### ISSUE THREAD

**Issue by rikkaka** [hardhackerlabs/oh-my-nvim#11]
https://github.com/hardhackerlabs/oh-my-nvim/blob/c77ddfede1e16b9ac9f6611773f4ec0e98bdee2a/lua/plugins/lspconfig/config.lua#L32

https://github.com/hardhackerlabs/oh-my-nvim/blob/c77ddfede1e16b9ac9f6611773f4ec0e98bdee2a/lua/custom_keys.lua#L11

These two keymaps are conflicting. It's better to set `vim.lsp.buf.signature_help` to another keymap.

**Comment by skoowoo** [comment]
Thanks for your feedback, I have fixed it.
