### ISSUE TITLE
:Notifications command is unreadable (doesn't fit to screen)

### ISSUE THREAD

**Issue by xerenahmed** [hardhackerlabs/oh-my-nvim#17]
Plus, I can't rename directories that has files inside it.

![image](https://github.com/hardhackerlabs/oh-my-nvim/assets/35738714/b5747b02-68d4-4e5e-97e3-9f8ae8d38612)

**Comment by skoowoo** [comment]
Now, You can use command `:NoiceLast` to view the error message.

Also, I might remove the Noice plugin, it makes viewing the error message more difficult.
