### ISSUE TITLE
在neovide中,  横向滑动会超出最大的范围

### ISSUE THREAD

**Issue by Liloupar** [hardhackerlabs/oh-my-nvim#4]
举个例子
在开屏欢迎页那个地方, 触摸板双指左右滑动即可触发这个问题.
按理说那个页面完全没有超出屏幕. 不需要左右滑动的...

**Comment by skoowoo** [comment]
我复现了你的问题，不知道是不是 neovide 的问题，我看一下。

**Comment by zohar-soul** [comment]
> 我复现了你的问题，不知道是不是 neovide 的问题，我看一下。

我搜了下issue, 看起来大概率是neovide的问题
https://github.com/neovide/neovide/issues/1609
视频里也是这个现象

**Comment by skoowoo** [comment]
> 
因为 neovide 中文输入法的问题，我到现在也没认真使用它。

**Comment by zohar-soul** [comment]
> 因为 neovide 中文输入法的问题，我到现在也没认真使用它。

我是看 readme 上写着推荐用 neovide
