### ISSUE TITLE
Icons won't display properly

### ISSUE THREAD

**Issue by opabravo** [hardhackerlabs/oh-my-nvim#7]
#### Issue Description

Followed the exact instructions in README.md to setup oh-my-nvim, 

But all the icons in nvim did not display properly.

#### Environment

- OS : Debian Jessie
- NVIM v0.9.1
- `TERM=tmux-256color`

#### Issue POV

![image](https://github.com/hardhackerlabs/oh-my-nvim/assets/21262207/969d941f-4fa6-4f06-914a-dc7dda657612)

**Comment by skoowoo** [comment]
Make sure you install and use nerd font. Refer to https://www.nerdfonts.com/font-downloads.

the icon requires font support.

**Comment by opabravo** [comment]
> Make sure you install and use nerd font. Refer to https://www.nerdfonts.com/font-downloads.
> 
> the icon requires font support.

Thanks for the reply,

I Have downloaded https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hack.zip

And extract the ttf to `~/.local/share/fonts` then used `fc-cache -f -v` to flush caches

But still the same

![image](https://github.com/hardhackerlabs/oh-my-nvim/assets/21262207/88fce982-14a5-4ab8-a696-d3f6615a325b)

**Comment by opabravo** [comment]
Hi

> > Make sure you install and use nerd font. Refer to https://www.nerdfonts.com/font-downloads.
> > the icon requires font support.
> 
> Thanks for the reply,
> 
> I Have downloaded https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hack.zip
> 
> And extract the ttf to `~/.local/share/fonts` then used `fc-cache -f -v` to flush caches
> 
> But still the same
> 
> ![image](https://user-images.githubusercontent.com/21262207/256959705-88fce982-14a5-4ab8-a696-d3f6615a325b.png)

Edit:

I found out it works fine in Gnome terminal, it just wont work in tmux
