### ISSUE TITLE
Conflicting keys in costum_keys

### ISSUE THREAD

**Issue by rikkaka** [hardhackerlabs/oh-my-nvim#9]
https://github.com/hardhackerlabs/oh-my-nvim/blob/c77ddfede1e16b9ac9f6611773f4ec0e98bdee2a/lua/custom_keys.lua#L16

https://github.com/hardhackerlabs/oh-my-nvim/blob/c77ddfede1e16b9ac9f6611773f4ec0e98bdee2a/lua/custom_keys.lua#L42

These two keys are conflicting and it can cause some problem like the keys of BufferLinePick cannot appear correctly (which I have met).

**Comment by skoowoo** [comment]
Thanks for your feedback, I have fixed it.
